version: "3.4"

services:
  publicapi:
    image: publicapi
    build:
      context: .
      dockerfile: src/PublicAPI/Dockerfile

  postgres-db:
    image: postgres

  mediamtx:
    image: bluenviron/mediamtx

  # webspa:
  #   build:
  #     context: ./src/WebSPA
  #     dockerfile: Dockerfile

volumes:
  pgdata:
